# Generated by Django 4.2 on 2023-04-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
